version: '3.8'

services:
  moneyhunter-backend:
    build: .
    container_name: moneyhunter-backend
    ports:
      - "8000:8000"
    restart: always
    environment:
      - TZ=Asia/Seoul
      - DB_HOST=host.docker.internal # 컨테이너에서 호스트 DB 접근
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - .env
      - ./logs:/app/logs

  moneyhunter-frontend:
    build:
      context: ./src/frontend
      dockerfile: Dockerfile
    container_name: moneyhunter-dashboard
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - moneyhunter-backend
